env:
  - PKG_DIR=/usr/lib/swipl/pack

before_script:
  - sudo apt-add-repository ppa:swi-prolog/stable -y
  - sudo apt-get update -q
  - sudo apt-get install swi-prolog-nox curl autoconf libtool zlib1g zlib1g-dev python
  - git clone --branch v1.3.3 https://github.com/rdfhdt/hdt-cpp.git
  - git clone --branch v0.30.0 https://github.com/drobilla/serd.git
  - cd serd && ./waf configure && ./waf && sudo ./waf install
  - cd ../hdt-cpp && ./autogen.sh && ./configure && make -j4 && sudo make install && sudo ldconfig
  - cd ../ && echo "pack_remove('hdt')." | swipl
  - echo "pack_install('https://github.com/GavinMendelGleason/hdt.git',[package_directory('$PKG_DIR'),interactive(false)])." | swipl
  - echo "pack_install(mavis,[package_directory('$PKG_DIR'),interactive(false)])." | swipl

script:
  - swipl -g main ./utils/initialize_database -k root -s localhost
