services:
  - docker

language: shell

stages:
  - build
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: build
    - script:
        - docker build -t terminusdb/terminus-server:latest .
        - docker run -it --rm terminusdb/terminus-server:latest bash -c "/app/terminusdb/utils/initialize_database -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl test"

    - stage: deploy
      script:
        - docker build -t terminusdb/terminus-server:latest .
        - docker run -it terminusdb/terminus-server bash -c "/app/terminusdb/utils/initialize_database -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl test"
        - echo "$DOCKER_PASS" | docker login -u terminusdb --password-stdin
        - docker push terminusdb/terminus-server:latest

notifications:
  irc:
    - "chat.freenode.net##terminusdb"
