services:
  - docker

language: shell

env:
  - TERMINUSDB_SERVER_JWT_PUBLIC_KEY_PATH=test/public_key_test.key.pub
  - TERMINUSDB_SERVER_JWT_PUBLIC_KEY_ID=testkey

stages:
  - build
  - name: deploy
    if: branch = master AND type != pull_request
  - name: deploy_dev
    if: branch = dev AND type != pull_request
  - name: deploy_canary
    if: branch = canary AND type != pull_request
  - name: deploy_tag
    if: tag =~ ^v AND type != pull_request

jobs:
  include:
    - stage: build
    - script:
        - docker build -t terminusdb/terminus-server:latest .
        - docker run -it terminusdb/terminus-server:latest bash -c "/app/terminusdb/utils/db_init -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl"

    - stage: deploy
      script:
        - docker build -t terminusdb/terminus-server:latest .
        - docker run -it terminusdb/terminus-server bash -c "/app/terminusdb/utils/db_init -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl"
        - echo "$DOCKER_PASS" | docker login -u terminusdb --password-stdin
        - docker push terminusdb/terminus-server:latest

    - stage: deploy_dev
      script:
        - docker build -t terminusdb/terminus-server:dev .
        - docker run -it terminusdb/terminus-server:dev bash -c "/app/terminusdb/utils/db_init -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl"
        - echo "$DOCKER_PASS" | docker login -u terminusdb --password-stdin
        - docker push terminusdb/terminus-server:dev

    - stage: deploy_canary
      script:
        - docker build -t terminusdb/terminus-server:canary .
        - docker run -it terminusdb/terminus-server:canary bash -c "/app/terminusdb/utils/db_init -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl"
        - bash .ci/trigger_canary.sh
        - echo "$DOCKER_PASS" | docker login -u terminusdb --password-stdin
        - docker push terminusdb/terminus-server:canary

    - stage: deploy_tag
      script:
        - docker build -t "terminusdb/terminus-server:$TRAVIS_TAG" .
        - docker run -it "terminusdb/terminus-server:$TRAVIS_TAG" bash -c "/app/terminusdb/utils/db_init -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl"
        - echo "$DOCKER_PASS" | docker login -u terminusdb --password-stdin
        - docker push "terminusdb/terminus-server:$TRAVIS_TAG"
