services:
  - docker

language: shell

stages:
  - build
  - name: deploy
    if: branch = master
  - name: deploy_dev
    if: branch = dev
  - name: deploy_tag
    if: tag =~ ^v

jobs:
  include:
    - stage: build
    - script:
        - docker build -t terminusdb/terminus-server:latest .
        - docker run -it --rm terminusdb/terminus-server:latest bash -c "/app/terminusdb/utils/db_util -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl test"

    - stage: deploy
      script:
        - docker build -t terminusdb/terminus-server:latest .
        - docker run -it terminusdb/terminus-server bash -c "/app/terminusdb/utils/db_util -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl test"
        - echo "$DOCKER_PASS" | docker login -u terminusdb --password-stdin
        - docker push terminusdb/terminus-server:latest

    - stage: deploy_dev
      script:
        - docker build -t terminusdb/terminus-server:dev .
        - docker run -it terminusdb/terminus-server:dev bash -c "/app/terminusdb/utils/db_util -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl test"
        - echo "$DOCKER_PASS" | docker login -u terminusdb --password-stdin
        - docker push terminusdb/terminus-server:dev

    - stage: deploy_tag
      script:
        - docker build -t "terminusdb/terminus-server:$TRAVIS_TAG" .
        - docker run -it "terminusdb/terminus-server:$TRAVIS_TAG" bash -c "/app/terminusdb/utils/db_util -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl test"
        - echo "$DOCKER_PASS" | docker login -u terminusdb --password-stdin
        - docker push "terminusdb/terminus-server:$TRAVIS_TAG"


notifications:
  irc:
    - "chat.freenode.net##terminusdb"
