services:
  - docker

language: shell

env:
  - DOCKERENVS="-e TERMINUSDB_SERVER_JWT_PUBLIC_KEY_PATH=test/public_key_test.key.pub -e TERMINUSDB_SERVER_JWT_PUBLIC_KEY_ID=testkey -e TERMINUSDB_HTTPS_ENABLED=false"

stages:
  - build
  - name: deploy
    if: branch IN (dev, canary, rc) AND type != pull_request
  - name: deploy_tag
    if: tag =~ ^v AND type != pull_request
  - trigger_appimage

jobs:
  include:
    - stage: build
      script:
        - docker build -t terminusdb/terminusdb-server:latest .
        - docker run $DOCKERENVS -it terminusdb/terminusdb-server:latest bash -c "/app/terminusdb/utils/db_init -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl"

    - stage: deploy
      script:
        - docker build -t "terminusdb/terminusdb-server:$TRAVIS_BRANCH" .
        - echo "$DOCKER_PASS" | docker login -u terminusdb --password-stdin
        - docker push "terminusdb/terminusdb-server:$TRAVIS_BRANCH"

    - stage: deploy_tag
      script:
        - docker build -t "terminusdb/terminusdb-server:$TRAVIS_TAG" .
        - echo "$DOCKER_PASS" | docker login -u terminusdb --password-stdin
        - docker push "terminusdb/terminusdb-server:$TRAVIS_TAG"
        - docker tag "terminusdb/terminusdb-server:$TRAVIS_TAG" "terminusdb/terminusdb-server:latest"
        - docker push "terminusdb/terminusdb-server:latest"

    - stage: trigger_appimage
      script:
        - bash .ci/trigger_appimage.sh
