services:
  - docker

language: shell

stages:
  - build
  - name: deploy
    if: branch = master
  - name: deploy_dev
    if: branch = dev
  - name: deploy_tag
    if: tag =~ ^v

jobs:
  include:
    - stage: build
    - script:
        - docker build -t terminusdb/terminus-server:latest .
        - docker run -it --rm terminusdb/terminus-server:latest bash -c "/app/terminusdb/utils/db_util -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl test"

    - stage: deploy
      script:
        - docker build -t terminusdb/terminus-server:latest .
        - docker run -it terminusdb/terminus-server bash -c "/app/terminusdb/utils/db_util -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl test"
        - echo "$DOCKER_PASS" | docker login -u terminusdb --password-stdin
        - docker push terminusdb/terminus-server:latest

    - stage: deploy_dev
      script:
        - docker build -t terminusdb/terminus-server:dev .
        - docker run -it terminusdb/terminus-server:dev bash -c "/app/terminusdb/utils/db_util -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl test"
        - echo "$DOCKER_PASS" | docker login -u terminusdb --password-stdin
        - docker push terminusdb/terminus-server:dev

    - stage: deploy_tag
      script:
        - docker build -t "terminusdb/terminus-server:$TRAVIS_TAG" .
        - docker run -it "terminusdb/terminus-server:$TRAVIS_TAG" bash -c "/app/terminusdb/utils/db_util -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl test"
        - echo "$DOCKER_PASS" | docker login -u terminusdb --password-stdin
        - docker push "terminusdb/terminus-server:$TRAVIS_TAG"


notifications:
  irc:
    - "chat.freenode.net##terminusdb"
  slack:
    rooms:
      secure: Zshj9zGozlzkeAvsLHIH7ibMBC+//R0rz0zUbv9iA5pJ/U+oT7Hp3wAlJrehENZQNvcAfxjxvqQmWLjFRpEyqkuRRt3Luex1wNDMjAT5F1sC6X6C+3zLJXh+tjoEFWEJjj5Q1caFK/q9X6nlfjOxGYisdIZ3BdfJERR2tw9avspR6UKDsAmEEkwTLF/NF+LYFKvMkTdChf0gyA8q603O1hyodx4EU+1bmVv7t9pcxCdY2zQO3mLMO4WmzaqT2+6eaigSd7TXEcmZFBwvFn7r9polhJ0kbYQu6YIJQDqhKlDqpr45M/AgcaLiBca7gTPMCRAyJjWhjNrx7eUVE7+H5ip2i2QtA07UnvySXkdSfM0xxyqauJG2eke8N9xLRQ5teIzNmi51RuZ2ppzpXvcXqeg8eXEL30qVEr/cA7LWh+xytEUHaxOU2pujCUI9whwcWqK5ucNdGc2SISO85NiIF4SUGPmsNIBqIbWYqlrio0m1v2lOaHWKdAerJOacAHEGO127CowNQNBVkXDAfJysMIsOuQp8V7yPleVNZJSYkvmRoYNtDF1LAKnWkB3MkgNWoAj+rZm2FYEEx70jiu254Y1Fkv765hxu4V5fSGhzbGxulcss3RDOzGGLkydPBKoXXOobY9/DpdgVI1keVc2CeRbp/KuM6Fjs+Yfa3QejI1w=
