services:
  - docker

script:
  - docker build -t terminusdb/terminus-server:latest .
  - docker run -it terminusdb/terminus-server bash -c "/app/terminusdb/utils/initialize_database -k root -s localhost && swipl -g run_tests -g halt /app/terminusdb/start.pl test"
